DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS wordlists;
DROP TABLE IF EXISTS queries;
DROP TABLE IF EXISTS macros;
DROP TABLE IF EXISTS patterns;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE wordlists (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  words TEXT NOT NULL,
  p_att TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE queries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  query TEXT NOT NULL,
  anchors TEXT,
  regions TEXT,
  pattern INTEGER,
  FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE macros (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  macro TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE patterns (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  name TEXT,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  template TEXT NOT NULL,
  explanation TEXT,
  FOREIGN KEY (author_id) REFERENCES users (id)
);
